^
[Error:   x Unexpected eof
    ,-[31:1]
 28 | };
 29 |
 30 | export default nextConfig;
 31 | ```
    `----

Caused by:
    Syntax Error] {
  code: 'GenericFailure'
}

Node.js v20.19.0

<IDX> ✘ Preview failed to start
<IDX> Starting preview...
Waiting for your web server to start serving

> nextn@0.1.0 dev
> next dev --turbopack -p 9002 --port 9002 --hostname 0.0.0.0

Error: node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error:   x Unexpected eof
    ,-[31:1]
 28 | };
 29 |
 30 | export default nextConfig;
 31 | ```
    `----

Caused by:
    Syntax Error] {
  code: 'GenericFailure'
}

Node.js v20.19.0

<IDX> ✘ Preview failed to start
<IDX> Starting preview...
Waiting for your web server to start serving

> nextn@0.1.0 dev
> next dev --turbopack -p 9002 --port 9002 --hostname 0.0.0.0

Error: node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error:   x Unexpected eof
    ,-[31:1]
 28 | };
 29 |
 30 | export default nextConfig;
 31 | ```
    `----

Caused by:
    Syntax Error] {
  code: 'GenericFailure'
}

Node.js v20.19.0

<IDX> ✘ Preview failed to start
<IDX> Starting preview...
Waiting for your web server to start serving

> nextn@0.1.0 dev
> next dev --turbopack -p 9002 --port 9002 --hostname 0.0.0.0

Error: node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error:   x Unexpected eof
    ,-[31:1]
 28 | };
 29 |
 30 | export default nextConfig;
 31 | ```
    `----

Caused by:
    Syntax Error] {
  code: 'GenericFailure'
}

Node.js v20.19.0

<IDX> ✘ Preview failed to start

Try Again

Show Complete Logs